apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "haproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "haproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
        {{- range .Values.services }}
            - name: port-{{ .port }}
              containerPort: {{ .port }}
              protocol: TCP
        {{- end }}
          livenessProbe:
            httpGet:
              path: /stats
              port: 9000
          readinessProbe:
            httpGet:
              path: /stats
              port: 9000
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
        - name: {{ .Chart.Name }}-dns
          image: "{{ .Values.dnsmasq.image.repository }}:{{ .Values.dnsmasq.image.tag }}"
          imagePullPolicy: {{ .Values.dnsmasq.image.pullPolicy }}
          securityContext:
            runAsUser: 100
          args:
            - --port
            - "10053"
            - --log-facility=/dev/stdout
          #  - -q # Log all queries for debugging
          resources:
{{ toYaml .Values.dnsmasq.resources | indent 12 }}
        - name: {{ .Chart.Name }}-log
          image: "{{ .Values.log.image.repository }}:{{ .Values.log.image.tag }}"
          imagePullPolicy: {{ .Values.log.image.pullPolicy }}
          resources:
{{ toYaml .Values.log.resources | indent 12 }}
      volumes:
        - name: haproxy-config
          configMap:
            name: {{ include "haproxy.fullname" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
