apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (contains "LoadBalancer" .Values.service.type) .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end}}
  ports:
  {{- range .Values.services }}
    - port: {{ .externalPort | default (.port) }}
      targetPort: {{ .port }}
      protocol: TCP
      name: port-{{ .port }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
